import {IPaginationParam} from 'src/react/lib/ajax';
import {PaymentTransaction} from './api-payments.type';

export interface IIndexMerchantFilters extends IPaginationParam {
  name?: string;
}

export interface IMerchant {
  name: string;
  merchantId: string;
}

export enum TransactionSubType {
  CHARGE_WALLET = 'CHARGE_WALLET',
  CHARGE_BOOST = 'CHARGE_BOOST',
  REFUND_BOOST = 'REFUND_BOOST',
  REFUND_WALLET = 'REFUND_WALLET',
  CHARGE_LOYALTY = 'CHARGE_LOYALTY',
  REFUND_LOYALTY = 'REFUND_LOYALTY',
  CHARGE_CARD = 'CHARGE_CARD',
  REFUND_CARD = 'REFUND_CARD',
  CHARGE_GIFT_CARD = 'CHARGE_GIFT_CARD',
  REFUND_GIFT_CARD = 'REFUND_GIFT_CARD',
  CHARGE_LOYALTY_CARD = 'CHARGE_LOYALTY_CARD',
  REFUND_LOYALTY_CARD = 'REFUND_LOYALTY_CARD',
  CHARGE_FLEET_CARD = 'CHARGE_FLEET_CARD',
  REFUND_FLEET_CARD = 'REFUND_FLEET_CARD',
  TRANSFER_MERCHANT_BONUS_WALLET = 'TRANSFER_MERCHANT_BONUS_WALLET',
  TRANSFER_REFUND_MERCHANT_BONUS_WALLET = 'TRANSFER_REFUND_MERCHANT_BONUS_WALLET',
  TRANSFER_MERCHANT_TO_PREPAID = 'TRANSFER_MERCHANT_TO_PREPAID',
  TRANSFER_MERCHANT_PREPAID_TO_CARD = 'TRANSFER_MERCHANT_PREPAID_TO_CARD',
  TRANSFER_MERCHANT_CARD_TO_PREPAID = 'TRANSFER_MERCHANT_CARD_TO_PREPAID',
  TRANSFER_MERCHANT_AVAILABLE_TO_CARD = 'TRANSFER_MERCHANT_AVAILABLE_TO_CARD',
  COLLECTION_GIFT_CARD_TOPUP = 'COLLECTION_GIFT_CARD_TOPUP',
  COLLECTION_GIFT_CARD_TOPUP_CANCEL = 'COLLECTION_GIFT_CARD_TOPUP_CANCEL',
  COLLECTION_LOYALTY_CARD_TOPUP = 'COLLECTION_LOYALTY_CARD_TOPUP',
  COLLECTION_LOYALTY_CARD_TOPUP_CANCEL = 'COLLECTION_LOYALTY_CARD_TOPUP_CANCEL',
  COLLECTION_FLEET_CARD_TOPUP = 'COLLECTION_FLEET_CARD_TOPUP',
  COLLECTION_FLEET_CARD_TOPUP_CANCEL = 'COLLECTION_FLEET_CARD_TOPUP_CANCEL',
  EXTERNAL_TOPUP_AVAILABLE = 'EXTERNAL_TOPUP_AVAILABLE',
  EXTERNAL_TOPUP_PREPAID = 'EXTERNAL_TOPUP_PREPAID',
  EXTERNAL_ADJUSTMENT_AVAILABLE = 'EXTERNAL_ADJUSTMENT_AVAILABLE',
  EXTERNAL_ADJUSTMENT_PREPAID = 'EXTERNAL_ADJUSTMENT_PREPAID',
  BULK_TOPUP_AVAILABLE = 'BULK_TOPUP_AVAILABLE',
  BULK_TOPUP_PREPAID = 'BULK_TOPUP_PREPAID',
  BULK_ADJUSTMENT_AVAILABLE = 'BULK_ADJUSTMENT_AVAILABLE',
  BULK_ADJUSTMENT_PREPAID = 'BULK_ADJUSTMENT_PREPAID',
}

export enum TransactionType {
  TOPUP = 'TOPUP',
  CHARGE = 'CHARGE',
  REFUND = 'REFUND',
  PAYOUT = 'PAYOUT',
  TOPUP_REFUND = 'TOPUP_REFUND',
  ADJUSTMENT = 'ADJUSTMENT',
  EXTERNAL_ADJUSTMENT = 'EXTERNAL_ADJUSTMENT',
  TRANSFER = 'TRANSFER',
  WITHDRAWAL = 'WITHDRAWAL',
  DISPUTE = 'DISPUTE',
  EXTERNAL_TOPUP = 'EXTERNAL_TOPUP',
}

export interface MerchantTransaction extends PaymentTransaction {
  attributes?: {
    merchantName?: string;
  };
  transactionUid: string;
  subType: TransactionSubType;
}
