import * as _ from 'lodash';
import {IMerchantCategoryCode} from 'src/shared/interfaces/merchant.interface';

/* eslint-disable */
// prettier-ignore
export const MerchantCategoryCodes: IMerchantCategoryCode[] = [
  {code: '0742', desc: 'Veterinary services'},
  {code: '0763', desc: 'Agricultural co-operative'},
  {code: '0780', desc: 'Landscaping and horticultural services'},
  {code: '1520', desc: 'General contractors - residential & commercial'},
  {code: '1711', desc: 'Heating, plumbing, and air conditioning contractors'},
  {code: '1731', desc: 'Electrical contractors'},
  {code: '1740', desc: 'Masonry, stonework, tile setting, plastering & insulation contractors'},
  {code: '1750', desc: 'Carpentry contractors'},
  {code: '1761', desc: 'Roofing and siding contractors'},
  {code: '1771', desc: 'Concrete work contractors'},
  {code: '1799', desc: 'Special trade contractors (not elsewhere classified)'},
  {code: '2741', desc: 'Miscellaneous publishing and printing'},
  {code: '2791', desc: 'Typesetting, plate making, and related services'},
  {code: '2842', desc: 'Specialty cleaning, polishing, & sanitation preparations'},
  {code: '3357', desc: 'Hertz'},
  {code: '3359', desc: 'Payless car rental'},
  {code: '3366', desc: 'Budget rent-a-car'},
  {code: '3370', desc: 'Rent-a-wreck'},
  {code: '3385', desc: 'Tropical rent-a-car'},
  {code: '3389', desc: 'Avis rent-a-car'},
  {code: '3390', desc: 'Dollar rent-a-car'},
  {code: '3393', desc: 'National car rental'},
  {code: '3395', desc: 'Thrifty car rental'},
  {code: '3398', desc: 'Econo-car rent-a-car'},
  {code: '3501', desc: 'Holiday Inns'},
  {code: '3502', desc: 'Best Western'},
  {code: '3503', desc: 'Sheraton'},
  {code: '3504', desc: 'Hilton'},
  {code: '3506', desc: 'Golden Tulip'},
  {code: '3507', desc: 'Friendship Inns'},
  {code: '3508', desc: 'Quality International'},
  {code: '3509', desc: 'Marriott'},
  {code: '3510', desc: 'Days Inns'},
  {code: '3512', desc: 'Intercontinental'},
  {code: '3515', desc: 'Rodeway Inns'},
  {code: '3516', desc: 'La Quinta Motor Inns'},
  {code: '3517', desc: 'Americana Hotels'},
  {code: '3520', desc: 'Meridien'},
  {code: '3527', desc: 'Downtowner Passport'},
  {code: '3528', desc: 'Red Lion'},
  {code: '3535', desc: 'Hilton International'},
  {code: '3536', desc: 'AMFAC Hotels'},
  {code: '3539', desc: 'Summerfield Suites Hotels'},
  {code: '3542', desc: 'Royal Hotels'},
  {code: '3543', desc: 'Four Seasons Hotels'},
  {code: '3546', desc: 'Hotel Sierra'},
  {code: '3550', desc: 'Regal 8 Inns'},
  {code: '3562', desc: 'Comfort Hotel International'},
  {code: '3565', desc: 'Relax Inns'},
  {code: '3573', desc: 'Sandman Hotels'},
  {code: '3574', desc: 'Venture Inn'},
  {code: '3575', desc: 'Vagabond Hotels'},
  {code: '3579', desc: 'Hotel Mercure'},
  {code: '3588', desc: 'Helmsley Hotels'},
  {code: '3590', desc: 'Fairmont Hotels Corporation'},
  {code: '3591', desc: 'Sonesta International Hotels'},
  {code: '3592', desc: 'Omni International'},
  {code: '3595', desc: 'Hospitality Inns'},
  {code: '3615', desc: 'Travelodge Motels'},
  {code: '3631', desc: 'Sleep Inn'},
  {code: '3637', desc: 'Ramada Inns'},
  {code: '3638', desc: 'Howard Johnson'},
  {code: '3641', desc: 'Sofitel Hotels'},
  {code: '3644', desc: 'Econo-Travel Motor Hotel'},
  {code: '3648', desc: 'De Vere Hotels'},
  {code: '3649', desc: 'Radisson'},
  {code: '3650', desc: 'Red Roof Inns'},
  {code: '3652', desc: 'Embassy Hotels'},
  {code: '3654', desc: 'Loews Hotels'},
  {code: '3660', desc: 'Knights Inns'},
  {code: '3665', desc: 'Hampton Inns'},
  {code: '3681', desc: 'Adams Mark'},
  {code: '3684', desc: 'Budget Host Inn'},
  {code: '3685', desc: 'Budgetel'},
  {code: '3687', desc: 'Clarion Hotel'},
  {code: '3690', desc: 'Courtyard by Marriott'},
  {code: '3692', desc: 'Doubletree'},
  {code: '3693', desc: 'Drury Inn'},
  {code: '3694', desc: 'Economy Inns of America'},
  {code: '3695', desc: 'Embassy Suites'},
  {code: '3699', desc: 'Midway Motor Lodge'},
  {code: '3700', desc: 'Motel 6'},
  {code: '3703', desc: 'Residence Inns'},
  {code: '3704', desc: 'Royce Hotel'},
  {code: '3705', desc: 'Sandman Inns'},
  {code: '3706', desc: 'Shilo inns'},
  {code: '3707', desc: 'Shoney\'s Inns'},
  {code: '3709', desc: 'Super 8 Motels'},
  {code: '3715', desc: 'Fairfield Inns'},
  {code: '3716', desc: 'Carlton Hotels'},
  {code: '3722', desc: 'Wyndham'},
  {code: '3731', desc: 'Harrah\'s Hotels and Casinos'},
  {code: '3738', desc: 'Tropicana Resort and Casino'},
  {code: '3742', desc: 'Club Med'},
  {code: '3747', desc: 'Club Corp / Club Resorts'},
  {code: '3748', desc: 'Wellesley Inns'},
  {code: '3750', desc: 'Crowne Plaza Hotels'},
  {code: '3773', desc: 'The Venetian Resort Hotel Casino'},
  {code: '3783', desc: 'Town and Country Resort'},
  {code: '4011', desc: 'Freight Railways'},
  {code: '4111', desc: 'Local passenger transportation'},
  {code: '4112', desc: 'Passenger railways'},
  {code: '4119', desc: 'Ambulance services'},
  {code: '4121', desc: 'Taxicabs and limousines'},
  {code: '4131', desc: 'Bus lines'},
  {code: '4214', desc: 'Motor freight carriers and trucking'},
  {code: '4215', desc: 'Courier services'},
  {code: '4225', desc: 'Public warehousing and storage'},
  {code: '4411', desc: 'Steamship and cruise lines'},
  {code: '4457', desc: 'Boat rentals and leasing'},
  {code: '4468', desc: 'Marinas, marine service, and supplies'},
  {code: '4511', desc: 'Airlines and air carriers (not elsewhere classified)'},
  {code: '4582', desc: 'Airports, flying fields, and airport terminals'},
  {code: '4722', desc: 'Travel agencies and tour operators'},
  {code: '4784', desc: 'Toll and bridge fees'},
  {code: '4789', desc: 'Transportation services (not elsewhere classified)'},
  {code: '4812', desc: 'Telecommunication equipment and telephone sales'},
  {code: '4814', desc: 'Telecommunication service'},
  {code: '4815', desc: 'Visaphone'},
  {code: '4816', desc: 'Computer network / information services'},
  {code: '4821', desc: 'Telegraph services'},
  {code: '4829', desc: 'Wire Transfer Money Orders (WTMOS)'},
  {code: '4899', desc: 'Cable, satellite and other pay television, and radio services'},
  {code: '4900', desc: 'Utilities - electric, gas, water, sanitary'},
  {code: '5013', desc: 'Motor vehicle supplies and new parts'},
  {code: '5021', desc: 'Office and commercial furniture'},
  {code: '5039', desc: 'Construction materials (not elsewhere classified)'},
  {code: '5044', desc: 'Photographic, photocopy, microfilm equipment and supplies'},
  {code: '5045', desc: 'Computers and computer peripheral equipment and services'},
  {code: '5046', desc: 'Commercial equipment (not elsewhere classified)'},
  {code: '5047', desc: 'Medical, dental, ophthalmic, and hospital equipment and supplies'},
  {code: '5051', desc: 'Metal service centers and offices'},
  {code: '5065', desc: 'Electrical parts and equipment'},
  {code: '5072', desc: 'Hardware, equipment and supplies'},
  {code: '5074', desc: 'Plumbing and heating equipment and supplies'},
  {code: '5085', desc: 'Industrial supplies (not elsewhere classified)'},
  {code: '5094', desc: 'Precious stones, metals, watches, and jewelry'},
  {code: '5099', desc: 'Durable goods (not elsewhere classified)'},
  {code: '5111', desc: 'Stationery, office supplies, printing, and writing paper'},
  {code: '5122', desc: 'Drugs, drug proprietaries, and druggist sundries'},
  {code: '5131', desc: 'Piece goods, notions, and other dry goods'},
  {code: '5137', desc: 'Men\'s, women\'s, and children\'s uniforms, and commercial clothing'},
  {code: '5139', desc: 'Commercial footwear'},
  {code: '5169', desc: 'Chemicals and allied products (not elsewhere classified)'},
  {code: '5172', desc: 'Petroleum and petroleum products'},
  {code: '5192', desc: 'Books, periodicals, and newspapers'},
  {code: '5193', desc: 'Florist supplies, nursery stock, and flowers'},
  {code: '5198', desc: 'Paint, varnishes, and supplies'},
  {code: '5199', desc: 'Nondurable goods (not elsewhere classified)'},
  {code: '5200', desc: 'Home supply warehouse stores'},
  {code: '5211', desc: 'Lumber and building materials stores'},
  {code: '5231', desc: 'Glass, paint, and wallpaper stores'},
  {code: '5251', desc: 'Hardware stores'},
  {code: '5261', desc: 'Nurseries and lawn and garden supply stores'},
  {code: '5271', desc: 'Mobile home dealers'},
  {code: '5300', desc: 'Wholesale clubs'},
  {code: '5309', desc: 'Duty free stores'},
  {code: '5310', desc: 'Discount stores'},
  {code: '5311', desc: 'Department stores'},
  {code: '5331', desc: 'Variety stores'},
  {code: '5399', desc: 'Miscellaneous general merchandise'},
  {code: '5411', desc: 'Grocery stores and supermarkets'},
  {code: '5422', desc: 'Freezer and locker meat provisioners'},
  {code: '5441', desc: 'Candy, nut, and confectionery stores'},
  {code: '5451', desc: 'Dairy products stores'},
  {code: '5462', desc: 'Bakeries'},
  {code: '5499', desc: 'Miscellaneous food stores - convenience stores and specialty markets'},
  {code: '5511', desc: 'Car and truck dealers (new and used) sales, service, repairs, parts, and leasing'},
  {code: '5521', desc: 'Car and truck dealers (used only) sales, service, repairs, parts, and leasing'},
  {code: '5531', desc: 'Auto and home supply stores (no longer valid MCC)'},
  {code: '5532', desc: 'Automotive tire stores'},
  {code: '5533', desc: 'Automotive parts and accessories stores'},
  {code: '5541', desc: 'Service stations'},
  {code: '5542', desc: 'Automated fuel dispensers'},
  {code: '5551', desc: 'Boat dealers'},
  {code: '5561', desc: 'Camper, recreational and utility trailer dealers'},
  {code: '5571', desc: 'Motorcycle shops and dealers'},
  {code: '5592', desc: 'Motor homes dealers'},
  {code: '5598', desc: 'Snowmobile dealers'},
  {code: '5599', desc: 'Miscellaneous automotive, aircraft, and farm equipment dealers (not elsewhere classified)'},
  {code: '5611', desc: 'Men\'s and boy\'s clothing and accessories stores'},
  {code: '5621', desc: 'Women\'s ready-to-wear stores'},
  {code: '5631', desc: 'Women\'s accessory and specialty shops'},
  {code: '5641', desc: 'Children\'s and infant\'s wear stores'},
  {code: '5651', desc: 'Family clothing stores'},
  {code: '5655', desc: 'Sports and riding apparel stores'},
  {code: '5661', desc: 'Shoe stores'},
  {code: '5681', desc: 'Furriers and fur shops'},
  {code: '5691', desc: 'Men\'s and women\'s clothing stores'},
  {code: '5697', desc: 'Tailors, seamstresses, mending and alterations'},
  {code: '5698', desc: 'Wig and toupee stores'},
  {code: '5699', desc: 'Miscellaneous apparel and accessory shops'},
  {code: '5712', desc: 'Furniture, home furnishings, and equipment stores, excepting appliances'},
  {code: '5713', desc: 'Floor covering stores'},
  {code: '5714', desc: 'Drapery, window covering, and upholstery stores'},
  {code: '5718', desc: 'Fireplace, fireplace screens and accessories stores'},
  {code: '5719', desc: 'Miscellaneous home furnishing specialty stores'},
  {code: '5722', desc: 'Household appliance stores'},
  {code: '5732', desc: 'Electronics stores'},
  {code: '5733', desc: 'Music stores - musical instruments, pianos, and sheet music'},
  {code: '5734', desc: 'Computer software stores'},
  {code: '5735', desc: 'Record stores'},
  {code: '5811', desc: 'Caterers'},
  {code: '5812', desc: 'Eating places & restaurants'},
  {code: '5813', desc: 'Drinking places - bars, taverns, nightclubs, cocktail lounges, and discotheques'},
  {code: '5814', desc: 'Fast food restaurants'},
  {code: '5912', desc: 'Drug stores and pharmacies'},
  {code: '5921', desc: 'Package stores - beer, wine, and liquor'},
  {code: '5931', desc: 'Used merchandise and secondhand stores'},
  {code: '5932', desc: 'Antique shops - sales, repairs, and restoration services'},
  {code: '5933', desc: 'Pawn shops'},
  {code: '5935', desc: 'Wrecking and salvage yards'},
  {code: '5937', desc: 'Antique reproductions'},
  {code: '5940', desc: 'Bicycle shops - sales and service'},
  {code: '5941', desc: 'Sporting goods stores'},
  {code: '5942', desc: 'Book stores'},
  {code: '5943', desc: 'Stationery stores, office and school supply stores'},
  {code: '5944', desc: 'Jewelry stores, watches, clocks, and silverware stores'},
  {code: '5945', desc: 'Hobby, toy, and game shops'},
  {code: '5946', desc: 'Camera and photographic supply stores'},
  {code: '5947', desc: 'Gift, card, novelty and souvenir shops'},
  {code: '5948', desc: 'Luggage and leather goods stores'},
  {code: '5949', desc: 'Sewing needlework, fabric, and piece goods stores'},
  {code: '5950', desc: 'Glassware / crystal stores'},
  {code: '5960', desc: 'Direct marketing - insurance services'},
  {code: '5962', desc: 'Direct marketing - travel-related arrangement services (high risk MCC)'},
  {code: '5963', desc: 'Door-to-door sales'},
  {code: '5964', desc: 'Direct marketing - catalog merchant'},
  {code: '5965', desc: 'Direct marketing - combination catalog and retail merchant'},
  {code: '5966', desc: 'Direct marketing - outbound telemarketing merchant (high risk MCC)'},
  {code: '5967', desc: 'Direct marketing - inbound tele-services merchant (high risk MCC)'},
  {code: '5968', desc: 'Direct marketing - continuity/subscription merch.'},
  {code: '5969', desc: 'Direct marketing - other direct marketers (not elsewhere classified)'},
  {code: '5970', desc: 'Artists supply and craft shops'},
  {code: '5971', desc: 'Art dealers and galleries'},
  {code: '5972', desc: 'Stamp and coin stores'},
  {code: '5973', desc: 'Religious goods stores'},
  {code: '5975', desc: 'Hearing aids - sales, service, and supply'},
  {code: '5976', desc: 'Orthopedic goods - prosthetic devices'},
  {code: '5977', desc: 'Cosmetic stores'},
  {code: '5978', desc: 'Typewriters - sales, rentals, & service'},
  {code: '5983', desc: 'Fuel dealers - fuel oil, wood, coal, liquefied petroleum'},
  {code: '5992', desc: 'Florists'},
  {code: '5993', desc: 'Cigar stores and stands'},
  {code: '5994', desc: 'News dealers and newsstands'},
  {code: '5995', desc: 'Pet shops, pet foods and supplies stores'},
  {code: '5996', desc: 'Swimming pools - sales and service'},
  {code: '5997', desc: 'Electric razor stores'},
  {code: '5998', desc: 'Tent and awning shops'},
  {code: '5999', desc: 'Miscellaneous and specialty retail shops'},
  {code: '6010', desc: 'Financial institutions - manual cash disbursements'},
  {code: '6011', desc: 'Financial institutions - automated cash disbursements'},
  {code: '6012', desc: 'Financial institutions merchandise and services'},
  {code: '6051', desc: 'Non-financial institutions - foreign currency, money orders, and travelers cheques'},
  {code: '6211', desc: 'Security brokers / dealers'},
  {code: '6300', desc: 'Insurance sales, underwriting, & premiums'},
  {code: '6381', desc: 'Insurance premiums'},
  {code: '6399', desc: 'Insurance not elsewhere classified'},
  {code: '6513', desc: 'Real estate agents and managers - rentals'},
  {code: '7011', desc: 'Lodging - hotels, motels, resorts, and central reservation services (not elsewhere classified)'},
  {code: '7012', desc: 'Timeshares'},
  {code: '7032', desc: 'Sporting and recreational camps'},
  {code: '7033', desc: 'Trailer parks and campgrounds'},
  {code: '7210', desc: 'Laundry, cleaning, and garment services'},
  {code: '7211', desc: 'Laundries - family and commercial'},
  {code: '7216', desc: 'Dry cleaners'},
  {code: '7217', desc: 'Carpet and upholstery cleaning'},
  {code: '7221', desc: 'Photographic studios'},
  {code: '7230', desc: 'Beauty and barber shops'},
  {code: '7251', desc: 'Shoe repair shops, shoe shine parlors, and hat cleaning shops'},
  {code: '7261', desc: 'Funeral service and crematories'},
  {code: '7273', desc: 'Dating and escort services'},
  {code: '7276', desc: 'Tax preparation service'},
  {code: '7277', desc: 'Counseling services - debt, marriage, and personal'},
  {code: '7278', desc: 'Buying and shopping services and clubs'},
  {code: '7296', desc: 'Clothing rental - costumes, uniforms, and formal wear'},
  {code: '7297', desc: 'Massage parlors'},
  {code: '7298', desc: 'Health and beauty spas'},
  {code: '7299', desc: 'Miscellaneous personal services (not elsewhere classified)'},
  {code: '7311', desc: 'Advertising services'},
  {code: '7321', desc: 'Consumer credit reporting agencies'},
  {code: '7332', desc: 'Commercial photography, art, and graphics'},
  {code: '7333', desc: 'Commercial photography, art, and graphics'},
  {code: '7338', desc: 'Quick copy, reproduction and blueprinting services'},
  {code: '7339', desc: 'Stenographic and secretarial support'},
  {code: '7342', desc: 'Exterminating and disinfecting services'},
  {code: '7349', desc: 'Cleaning, maintenance, and janitorial services'},
  {code: '7361', desc: 'Employment agencies and temporary help services'},
  {code: '7372', desc: 'Computer programming, data processing, and integrated systems design services'},
  {code: '7375', desc: 'Information retrieval services'},
  {code: '7379', desc: 'Computer maintenance, repair, and services (not elsewhere classified)'},
  {code: '7392', desc: 'Management, consulting, and public relations services'},
  {code: '7393', desc: 'Detective agencies, protective services, and security services'},
  {code: '7394', desc: 'Equipment, tool, furniture, and appliance rental and leasing'},
  {code: '7395', desc: 'Photofinishing laboratories and photo developing'},
  {code: '7399', desc: 'Business services (not elsewhere classified)'},
  {code: '7512', desc: 'Automobile rental agency'},
  {code: '7513', desc: 'Truck and utility trailer rentals'},
  {code: '7519', desc: 'Motor home and recreational vehicle rentals'},
  {code: '7523', desc: 'Parking lots and garages'},
  {code: '7531', desc: 'Automotive body repair shops'},
  {code: '7534', desc: 'Tire retreading and repair shops'},
  {code: '7535', desc: 'Automotive paint shops'},
  {code: '7538', desc: 'Automotive service shops (non-dealer)'},
  {code: '7542', desc: 'Car washes'},
  {code: '7549', desc: 'Towing services'},
  {code: '7622', desc: 'Electronics repair shops'},
  {code: '7623', desc: 'Air conditioning and refrigeration repair shops'},
  {code: '7629', desc: 'Electrical and small appliance repair shops'},
  {code: '7631', desc: 'Watch, clock and jewelry repair'},
  {code: '7641', desc: 'Furniture - reupholstery, repair, and refinishing'},
  {code: '7692', desc: 'Welding services'},
  {code: '7699', desc: 'Miscellaneous repair shops and related services'},
  {code: '7829', desc: 'Motion picture and video tape production and distribution'},
  {code: '7832', desc: 'Motion picture theaters'},
  {code: '7841', desc: 'Video tape rental stores'},
  {code: '7911', desc: 'Dance halls, studios, and schools'},
  {code: '7922', desc: 'Theatrical producers and ticket agencies'},
  {code: '7929', desc: 'Bands, orchestras, and miscellaneous entertainers (not elsewhere classified)'},
  {code: '7932', desc: 'Billiard and pool establishments'},
  {code: '7933', desc: 'Bowling alleys'},
  {code: '7941', desc: 'Commercial sports, professional sports clubs, athletic fields, and sports promoters'},
  {code: '7991', desc: 'Tourist attractions and exhibits'},
  {code: '7992', desc: 'Public golf courses'},
  {code: '7993', desc: 'Video amusement game supplies'},
  {code: '7994', desc: 'Video game arcades / establishments'},
  {code: '7995', desc: 'Betting, including lottery tickets, casino gaming chips, off-track betting and wagers at race tracks'},
  {code: '7996', desc: 'Amusement parks, circuses, carnivals, and fortune tellers'},
  {code: '7997', desc: 'Membership clubs, country clubs, and private golf courses'},
  {code: '7998', desc: 'Aquariums, seaquariums, dolphinariums'},
  {code: '7999', desc: 'Recreation services (not elsewhere classified)'},
  {code: '8011', desc: 'Doctors and physicians (not elsewhere classified)'},
  {code: '8021', desc: 'Dentists and orthodontists'},
  {code: '8031', desc: 'Osteopaths'},
  {code: '8041', desc: 'Chiropractors'},
  {code: '8042', desc: 'Optometrists and ophthalmologists'},
  {code: '8043', desc: 'Opticians, optical goods, and eyeglasses'},
  {code: '8049', desc: 'Podiatrists and chiropodists'},
  {code: '8050', desc: 'Nursing and personal care facilities'},
  {code: '8062', desc: 'Hospitals'},
  {code: '8071', desc: 'Medical and dental laboratories'},
  {code: '8099', desc: 'Medical services and health practitioners (not elsewhere classified)'},
  {code: '8111', desc: 'Legal services and attorneys'},
  {code: '8211', desc: 'Elementary and secondary schools'},
  {code: '8220', desc: 'Colleges, universities, professional schools, and junior colleges'},
  {code: '8241', desc: 'Correspondence schools'},
  {code: '8244', desc: 'Business and secretarial schools'},
  {code: '8249', desc: 'Vocational and trade schools'},
  {code: '8299', desc: 'Schools and educational services (not elsewhere classified)'},
  {code: '8351', desc: 'Child care services'},
  {code: '8398', desc: 'Charitable and social service organizations'},
  {code: '8641', desc: 'Civic, social, and fraternal associations'},
  {code: '8651', desc: 'Political organizations'},
  {code: '8661', desc: 'Religious organizations'},
  {code: '8675', desc: 'Automobile associations'},
  {code: '8699', desc: 'Membership organizations (not elsewhere classified)'},
  {code: '8734', desc: 'Testing laboratories (non-medical testing)'},
  {code: '8911', desc: 'Architectural, engineering, and surveying services'},
  {code: '8931', desc: 'Accounting, auditing, and bookkeeping services'},
  {code: '8999', desc: 'Professional sevices (not elsewhere classified)'},
  {code: '9211', desc: 'Court costs, including alimony and child support'},
  {code: '9222', desc: 'Fines'},
  {code: '9223', desc: 'Bail and bond payments'},
  {code: '9311', desc: 'Tax payments'},
  {code: '9399', desc: 'Government services (not elsewhere classified)'},
  {code: '9402', desc: 'Postal services - government only'},
  {code: '9405', desc: 'US federal government agencies or departments'},
];
/* eslint-enable */

export const CombinedMerchantCategoryCodes = MerchantCategoryCodes.map((mcc) => {
  return {
    ...mcc,
    combined: mcc.code + ' - ' + mcc.desc,
  };
});

export const MerchantCategoryCodeToInfo = _.keyBy(CombinedMerchantCategoryCodes, 'code');

export const SETEL_MERCHANT_ID = '1';
