export enum ReportTypes {
  RECEIVABLES = 'RECEIVABLES',
  PAYABLES = 'PAYABLES',
  LIABILITIES = 'LIABILITIES',
  EQUITY = 'EQUITY',
  REFUNDS = 'REFUNDS',
  WITHDRAWALS = 'WITHDRAWALS',
  MBB_TRUSTEE = 'MBB_TRUSTEE',
}
