// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: true,
  isSetelWalletRolledOut: true,
  enableApiIamRoles: true,
  enableServiceWorker: false,
  isE2eTesting: false,
  enterprise: 'setel',
  useLegacyTreasury: {
    receivables: false,
  },
  enableLinkToPhysicalCard: false,
  isGenerateInvoiceToManualChargeEnabled: false,
  /**
   * a flag to indicate whether to show pages that completed development but not yet fully tested.
   */
  showBetaPages: false,
  setelUrl: 'https://admin.setel.my',
  setelWebDashboardUrl: 'https://dashboard.setel.my',
  pdbUrl: 'https://pdbadmin.setel.my',
  pdbWebDashboardUrl: 'https://pdbdashboard.setel.my',
  apiBaseUrl: 'https://api.prod.setel.my',
  paymentsApiBaseUrl: 'https://api.prod.setel.my',
  circlesApiBaseUrl: 'https://api.prod.setel.my',
  checkoutsApiBaseUrl: 'https://api.prod.setel.my',
  maintenanceApiBaseUrl: 'https://api.prod.setel.my',
  rewardsApiBaseUrl: 'https://api.prod.setel.my',
  accountsApiBaseUrl: 'https://api.prod.setel.my',
  loyaltyApiBaseUrl: 'https://api.prod.setel.my',
  stationsApiBaseUrl: 'https://api.prod.setel.my',
  orderApiBaseUrl: 'https://api.prod.setel.my',
  fuelApiBaseUrl: 'https://api.prod.setel.my',
  vouchersApiBaseUrl: 'https://api.prod.setel.my',
  storeApiBaseUrl: 'https://api.prod.setel.my',
  merchantsApiBaseUrl: 'https://api.prod.setel.my',
  settlementsApiBaseUrl: 'https://api.prod.setel.my',
  walletsApiBaseUrl: 'https://api.prod.setel.my',
  walletApiBaseUrl: 'https://api.prod.setel.my',
  budgetApiBaseUrl: 'https://api.prod.setel.my',
  balanceExpiryApiBaseUrl: 'https://api.prod.setel.my',
  ledgerApiBaseUrl: 'https://api.prod.setel.my',
  membershipApiBaseUrl: 'https://api.prod.setel.my',
  externalOrdersApiBaseUrl: 'https://api.prod.setel.my',
  processorApiBaseUrl: 'https://api.prod.setel.my',
  blacklistApiBaseUrl: 'https://api.prod.setel.my',
  verificationsApiBaseUrl: 'https://api.prod.setel.my',
  iamApiBaseUrl: 'https://api.prod.setel.my',
  acquirersApiBaseUrl: 'https://api.prod.setel.my',
  cardsApiBaseUrl: 'https://api.prod.setel.my',
  giftCardsApiBaseUrl: 'https://api.prod.setel.my',
  fleetCardsApiBaseUrl: 'https://api.prod.setel.my',
  workflowsApiBaseUrl: 'https://api.prod.setel.my',
  switchApiBaseUrl: 'https://api.prod.setel.my',
  attributesApiBaseUrl: 'https://api.prod.setel.my',
  companiesApiBaseUrl: 'https://api.prod.setel.my',
  vehicleApiBaseUrl: 'https://api.prod.setel.my',
  vehicleDirectoryApiBaseUrl: 'https://api.prod.setel.my',
  vehicleActivitiesApiBaseUrl: 'https://api.prod.setel.my',
  variablesBaseUrl: 'https://api.prod.setel.my',
  dealsBaseUrl: 'https://api.prod.setel.my/api/deals',
  reportsBaseUrl: 'https://api.prod.setel.my',
  opsApiBaseUrl: 'https://api.prod.setel.my',
  calendarsBaseUrl: 'https://api.prod.setel.my',
  terminalAPIBaseUrl: 'https://api.prod.setel.my',
  emailsBaseUrl: 'https://api.prod.setel.my',
  pointsRulesApiBaseUrl: 'https://api.prod.setel.my',
  feesApiBaseUrl: 'https://api.prod.setel.my',
  reloadsApiBaseUrl: 'https://api.prod.setel.my',
  rebatesApiBaseUrl: 'https://api.prod.setel.my',
  billingPlansApiBaseUrl: 'https://api.prod.setel.my',
  sitesBaseUrl: 'https://api.prod.setel.my',
  subsidyBaseUrl: 'https://api.prod.setel.my',
  circleBaseUrl: 'https://api.prod.setel.my',
  setelTerminalApiBaseUrl: 'https://api.prod.setel.my',
  terminalSwitchApiBaseUrl: 'https://api.prod.setel.my',
  parkingBaseUrl: 'https://api-prod.setel.com',
  partnerSftpBaseUrl: 'https://api.prod.setel.my',
  paymentAcceptanceApiBaseUrl: 'https://api.prod.setel.my',
  bnplBaseUrl: 'https://api.prod.setel.my',
};
