import {IBankInfo} from 'src/app/api-switch.service';

/* eslint-disable */
// prettier-ignore
export const BankInfos: IBankInfo[] = [
  {name: 'Affin Bank', id: 'affin_bank'},
  {name: 'Affin Islamic Bank', id: 'affin_islamic_bank'},
  {name: 'Agrobank', id: 'agrobank'},
  {name: 'Alliance Bank', id: 'alliance_bank'},
  {name: 'Alliance Islamic Bank', id: 'alliance_islamic_bank'},
  {name: 'Al-Rajhi Banking & Inv.Corp.(M) Bhd', id: 'al_rajhi'},
  {name: 'Ambank', id: 'ambank'},
  {name: 'AmIslamic Bank', id: 'amislamic'},
  {name: 'Bank Islam', id: 'bank_islam'},
  {name: 'Bank Kerjasama Rakyat', id: 'bank_kerjasama'},
  {name: 'Bank Muamalat', id: 'bank_muamalat'},
  {name: 'Bank of America', id: 'bank_of_america'},
  {name: 'Bank of China', id: 'bank_of_china'},
  {name: 'Bank Simpanan Nasional', id: 'bank_simpanan'},
  {name: 'Bank of Tokyo-Mitsubishi UFJ', id: 'bank_of_tokyo_mitsubishi_ufj'},
  {name: 'CIMB Bank', id: 'cimb_bank'},
  {name: 'CIMB Islamic Bank', id: 'cimb_islamic_bank'},
  {name: 'BNP Paribas', id: 'bnp_paribas'},
  {name: 'Citibank', id: 'citibank'},
  {name: 'Deutsche Bank', id: 'deutsche_bank'},
  {name: 'Hong Leong Bank', id: 'hong_leong_bank'},
  {name: 'Hong Leong Islamic Bank', id: 'hong_leong_islamic_bank'},
  {name: 'HSBC Bank', id: 'hsbc_bank'},
  {name: 'HSBC Amanah', id: 'hsbc_amanah'},
  {name: 'Industrial & Commercial Bank of China (ICBC)', id: 'industrial_commercial_bank_of_china'},
  {name: 'JP Morgan Chase', id: 'jp_morgan_chase'},
  {name: 'Kuwait Finance House', id: 'kuwait_finance_house'},
  {name: 'Maybank', id: 'maybank'},
  {name: 'Mizuho Bank', id: 'mizuho_bank'},
  {name: 'OCBC Bank', id: 'ocbc_bank'},
  {name: 'OCBC Al-Amin Bank', id: 'ocbc_al_amin_bank'},
  {name: 'Public Bank', id: 'public_bank'},
  {name: 'Public Islamic Bank', id: 'public_islamic_bank'},
  {name: 'RHB Bank', id: 'rhb_bank'},
  {name: 'RHB Islamic Bank', id: 'rhb_islamic_bank'},
  {name: 'Standard Chartered Bank', id: 'standard_chartered_bank'},
  {name: 'Standard Chartered Saadiq', id: 'standard_chartered_saadiq'},
  {name: 'Sumitomo Mitsui Banking Corporation', id: 'sumitomo_mitsui_banking_corporation'},
  {name: 'United Overseas Bank', id: 'united_overseas_bank'},
];
/* eslint-enable */
