export const ORDER_NULL = 'ORDER_NULL';

// Order Fuel
export const FUEL_ORDER_INIT = 'FUEL_ORDER_INIT';
export const FUEL_ORDER_INIT_SUCCESS = 'FUEL_ORDER_INIT_SUCCESS';
export const FUEL_ORDER_INIT_ERROR = 'FUEL_ORDER_INIT_ERROR';

export const FUEL_ORDER_TRANSACTION_STARTED = 'FUEL_ORDER_TRANSACTION_STARTED';
export const FUEL_ORDER_TRANSACTION_STARTED_SUCCESS = 'FUEL_ORDER_TRANSACTION_STARTED_SUCCESS';
export const FUEL_ORDER_TRANSACTION_STARTED_ERROR = 'FUEL_ORDER_TRANSACTION_STARTED_ERROR';
export const FUEL_ORDER_TRANSACTION_STARTED_NO_RESP = 'FUEL_ORDER_TRANSACTION_STARTED_NO_RESP';

export const FUEL_ORDER_PRE_AUTH_STARTED = 'FUEL_ORDER_PRE_AUTH_STARTED';
export const FUEL_ORDER_PRE_AUTH_STARTED_SUCCESS = 'FUEL_ORDER_PRE_AUTH_STARTED_SUCCESS';
export const FUEL_ORDER_PRE_AUTH_STARTED_ERROR = 'FUEL_ORDER_PRE_AUTH_STARTED_ERROR';
export const FUEL_ORDER_PRE_AUTH_STARTED_NO_RESP = 'FUEL_ORDER_PRE_AUTH_STARTED_NO_RESP';

export const FUEL_ORDER_FULFILL_STARTED = 'FUEL_ORDER_FULFILL_STARTED';
export const FUEL_ORDER_FULFILL_STARTED_SUCCESS = 'FUEL_ORDER_FULFILL_STARTED_SUCCESS';
export const FUEL_ORDER_FULFILL_STARTED_ERROR = 'FUEL_ORDER_FULFILL_STARTED_ERROR';
export const FUEL_ORDER_FULFILL_STARTED_NO_RESP = 'FUEL_ORDER_FULFILL_STARTED_NO_RESP';

export const FUEL_ORDER_FULFILL_CONFIRMATION_STARTED = 'FUEL_ORDER_FULFILL_CONFIRMATION_STARTED';
export const FUEL_ORDER_FULFILL_CONFIRMATION_SUCCESS = 'FUEL_ORDER_FULFILL_CONFIRMATION_SUCCESS';
export const FUEL_ORDER_FULFILL_CONFIRMATION_ERROR = 'FUEL_ORDER_FULFILL_CONFIRMATION_ERROR';

export const FUEL_ORDER_CHARGE = 'FUEL_ORDER_CHARGE';
export const FUEL_ORDER_CHARGE_SUCCESS = 'FUEL_ORDER_CHARGE_SUCCESS';
export const FUEL_ORDER_CHARGE_ERROR = 'FUEL_ORDER_CHARGE_ERROR';
export const FUEL_ORDER_CHARGE_NO_RESP = 'FUEL_ORDER_CHARGE_NO_RESP';

export const FUEL_ORDER_CONFIRM = 'FUEL_ORDER_CONFIRM';
export const FUEL_ORDER_CONFIRM_SUCCESS = 'FUEL_ORDER_CONFIRM_SUCCESS';
export const FUEL_ORDER_CONFIRM_ERROR = 'FUEL_ORDER_CONFIRM_ERROR';

// Order Store

export const STORE_ORDER_INIT = 'STORE_ORDER_INIT';
export const STORE_ORDER_INIT_SUCCESS = 'STORE_ORDER_INIT_SUCCESS';
export const STORE_ORDER_INIT_ERROR = 'STORE_ORDER_INIT_ERROR';

export const STORE_ORDER_PRE_AUTH = 'STORE_ORDER_PRE_AUTH';
export const STORE_ORDER_PRE_AUTH_SUCCESS = 'STORE_ORDER_PRE_AUTH_SUCCESS';
export const STORE_ORDER_PRE_AUTH_ERROR = 'STORE_ORDER_PRE_AUTH_ERROR';

export const STORE_ORDER_CONFIRM = 'STORE_ORDER_CONFIRM';
export const STORE_ORDER_CONFIRM_SUCCESS = 'STORE_ORDER_CONFIRM_SUCCESS';
export const STORE_ORDER_CONFIRM_ERROR = 'STORE_ORDER_CONFIRM_ERROR';

export const STORE_ORDER_FULFILL = 'STORE_ORDER_FULFILL';
export const STORE_ORDER_FULFILL_SUCCESS = 'STORE_ORDER_FULFILL_SUCCESS';
export const STORE_ORDER_FULFILL_ERROR = 'STORE_ORDER_FULFILL_ERROR';

// Common
export const ORDER_ISSUE_LOYALTY_POINTS = 'ORDER_ISSUE_LOYALTY_POINTS';
export const ORDER_ISSUE_LOYALTY_POINTS_SUCCESS = 'ORDER_ISSUE_LOYALTY_POINTS_SUCCESS';
export const ORDER_ISSUE_LOYALTY_POINTS_ERROR = 'ORDER_ISSUE_LOYALTY_POINTS_ERROR';

export const ORDER_CANCELED = 'ORDER_CANCELED';

export const ORDER_REFUND = 'ORDER_REFUND';

export const FUEL_ORDER_LOYALTY_POINTS_SETEL_SUCCESS = 'FUEL_ORDER_LOYALTY_POINTS_SETEL_SUCCESS';
export const FUEL_ORDER_LOYALTY_POINTS_PETRONAS_SUCCESS =
  'FUEL_ORDER_LOYALTY_POINTS_PETRONAS_SUCCESS';
export const FUEL_ORDER_LOYALTY_POINTS_PETRONAS_ERROR = 'FUEL_ORDER_LOYALTY_POINTS_PETRONAS_ERROR';
export const FUEL_ORDER_LOYALTY_POINTS_NO_RESP = 'FUEL_ORDER_LOYALTY_POINTS_NO_RESP';
export const FUEL_ORDER_LOYALTY_POINTS_SETEL_ERROR = 'FUEL_ORDER_LOYALTY_POINTS_SETEL_ERROR';
export const FUEL_ORDER_LOYALTY_POINTS_SETEL_NO_RESP = 'FUEL_ORDER_LOYALTY_POINTS_SETEL_NO_RESP';
export const FUEL_ORDER_LOYALTY_POINTS_PETRONAS_NO_RESP =
  'FUEL_ORDER_LOYALTY_POINTS_PETRONAS_NO_RESP';

export enum OrderStatus {
  created = 'Created',
  fulfillmentReady = 'Fuel Fulfillment Ready',
  fulfillmentStarted = 'Fuel Fulfillment Started',
  fulfillmentSuccess = 'Fuel Fulfillment Success',
  fulfillmentError = 'Fuel Fulfillment Error',
  confirmed = 'Confirmed',
  fulfilled = 'Fulfilled',
  refund = 'Refunded',
  cancelled = 'Cancelled',
  error = 'Error',
}

export enum stationStatus {
  active = 'active',
  inactive = 'inactive',
  maintenance = 'maintenance',
  'coming-soon' = 'coming-soon',
}

export enum vendorStationStatus {
  active = 'active',
  inactive = 'inactive',
}

export enum TransactionType {
  cancelAuthorize = 'Cancel authorize',
  // [TODO: Will reuse back once limit manual charge done ]
  // chargeByAmount = 'Charge by amount',
  chargeByInvoice = 'Charge by Invoice',
}

export enum LoyaltyType {
  issuePointByInvoice = 'Issue points by invoice',
  issuePointByAmount = 'Issue points by amount',
}

export const ORDER_STATUSES = {
  [OrderStatus.created]: [
    FUEL_ORDER_TRANSACTION_STARTED_SUCCESS,
    FUEL_ORDER_PRE_AUTH_STARTED,
    FUEL_ORDER_PRE_AUTH_STARTED_SUCCESS,
    FUEL_ORDER_FULFILL_STARTED,
  ],
  [OrderStatus.fulfillmentReady]: [FUEL_ORDER_FULFILL_STARTED_SUCCESS],
  [OrderStatus.fulfillmentStarted]: [FUEL_ORDER_FULFILL_CONFIRMATION_STARTED],
  [OrderStatus.fulfillmentSuccess]: [
    FUEL_ORDER_CHARGE,
    FUEL_ORDER_CHARGE_SUCCESS,
    FUEL_ORDER_CONFIRM,
    FUEL_ORDER_FULFILL_CONFIRMATION_SUCCESS,
  ],
  [OrderStatus.fulfillmentError]: [FUEL_ORDER_FULFILL_CONFIRMATION_ERROR],
  [OrderStatus.fulfilled]: [STORE_ORDER_FULFILL_SUCCESS],
  [OrderStatus.confirmed]: [
    FUEL_ORDER_CONFIRM_SUCCESS,
    STORE_ORDER_CONFIRM_SUCCESS,
    FUEL_ORDER_LOYALTY_POINTS_SETEL_SUCCESS,
    FUEL_ORDER_LOYALTY_POINTS_PETRONAS_SUCCESS,
    FUEL_ORDER_LOYALTY_POINTS_PETRONAS_ERROR,
    FUEL_ORDER_LOYALTY_POINTS_PETRONAS_NO_RESP,
    FUEL_ORDER_LOYALTY_POINTS_SETEL_ERROR,
    FUEL_ORDER_LOYALTY_POINTS_SETEL_NO_RESP,
  ],
  [OrderStatus.error]: [
    FUEL_ORDER_INIT_ERROR,
    FUEL_ORDER_TRANSACTION_STARTED_ERROR,
    FUEL_ORDER_PRE_AUTH_STARTED_ERROR,
    FUEL_ORDER_CONFIRM_ERROR,
    FUEL_ORDER_FULFILL_STARTED_ERROR,
    FUEL_ORDER_CHARGE_ERROR,
    STORE_ORDER_INIT_ERROR,
    STORE_ORDER_PRE_AUTH_ERROR,
    STORE_ORDER_CONFIRM_ERROR,
    STORE_ORDER_FULFILL_ERROR,
    FUEL_ORDER_TRANSACTION_STARTED_NO_RESP,
    FUEL_ORDER_PRE_AUTH_STARTED_NO_RESP,
    FUEL_ORDER_FULFILL_STARTED_NO_RESP,
    FUEL_ORDER_CHARGE_NO_RESP,
  ],
  [OrderStatus.cancelled]: [ORDER_CANCELED],
  [OrderStatus.refund]: [ORDER_REFUND],
};
