export enum PayoutBatchStatuses {
  PAYMENT_FILE_PROCESSING = 'PAYMENT_FILE_PROCESSING',
  PAYMENT_FILE_SUBMITTED = 'PAYMENT_FILE_SUBMITTED',
  ACK_SUCCEEDED = 'ACK_SUCCEEDED',
  ACK_PARTIAL_REJECTED = 'ACK_PARTIAL_REJECTED',
  ACK_REJECTED = 'ACK_REJECTED',
  ACK_INVALID = 'ACK_INVALID',
  PARTIAL_COMPLETED = 'PARTIAL_COMPLETED',
  COMPLETED = 'COMPLETED',
}
